/*
Copyright The Kubegene Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubegene.io/kubegene/pkg/apis/gene/v1alpha1"
	scheme "kubegene.io/kubegene/pkg/client/clientset/versioned/scheme"
)

// ExecutionsGetter has a method to return a ExecutionInterface.
// A group's client should implement this interface.
type ExecutionsGetter interface {
	Executions(namespace string) ExecutionInterface
}

// ExecutionInterface has methods to work with Execution resources.
type ExecutionInterface interface {
	Create(ctx context.Context, execution *v1alpha1.Execution, opts v1.CreateOptions) (*v1alpha1.Execution, error)
	Update(ctx context.Context, execution *v1alpha1.Execution, opts v1.UpdateOptions) (*v1alpha1.Execution, error)
	UpdateStatus(ctx context.Context, execution *v1alpha1.Execution, opts v1.UpdateOptions) (*v1alpha1.Execution, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Execution, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ExecutionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Execution, err error)
	ExecutionExpansion
}

// executions implements ExecutionInterface
type executions struct {
	client rest.Interface
	ns     string
}

// newExecutions returns a Executions
func newExecutions(c *ExecutionV1alpha1Client, namespace string) *executions {
	return &executions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the execution, and returns the corresponding execution object, and an error if there is any.
func (c *executions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Execution, err error) {
	result = &v1alpha1.Execution{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("executions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Executions that match those selectors.
func (c *executions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExecutionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ExecutionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("executions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested executions.
func (c *executions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("executions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a execution and creates it.  Returns the server's representation of the execution, and an error, if there is any.
func (c *executions) Create(ctx context.Context, execution *v1alpha1.Execution, opts v1.CreateOptions) (result *v1alpha1.Execution, err error) {
	result = &v1alpha1.Execution{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("executions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(execution).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a execution and updates it. Returns the server's representation of the execution, and an error, if there is any.
func (c *executions) Update(ctx context.Context, execution *v1alpha1.Execution, opts v1.UpdateOptions) (result *v1alpha1.Execution, err error) {
	result = &v1alpha1.Execution{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("executions").
		Name(execution.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(execution).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *executions) UpdateStatus(ctx context.Context, execution *v1alpha1.Execution, opts v1.UpdateOptions) (result *v1alpha1.Execution, err error) {
	result = &v1alpha1.Execution{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("executions").
		Name(execution.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(execution).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the execution and deletes it. Returns an error if one occurs.
func (c *executions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("executions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *executions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("executions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched execution.
func (c *executions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Execution, err error) {
	result = &v1alpha1.Execution{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("executions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
