kind: PersistentVolume
apiVersion: v1
metadata:
  name: sample-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /xsw/sample
    type: Directory
